### ISSUE TITLE
Missing logger-application dependency?

### ISSUE THREAD

**Issue by shorowit** [rubyjedi/soap4r#23]
I get the error that logger-application is missing. 

```
$ sudo gem install soap4r-ng
[sudo] password for shorowit:
Fetching: soap4r-ng-2.0.4.gem (100%)
Successfully installed soap4r-ng-2.0.4
Parsing documentation for soap4r-ng-2.0.4
Installing ri documentation for soap4r-ng-2.0.4
Done installing documentation for soap4r-ng after 5 seconds
1 gem installed

$ xsd2ruby.rb --xsd
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- logger-application (LoadError)
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /var/lib/gems/2.2.0/gems/soap4r-ng-2.0.4/bin/xsd2ruby.rb:7:in `<top (required)>'
        from /usr/local/bin/xsd2ruby.rb:23:in `load'
        from /usr/local/bin/xsd2ruby.rb:23:in `<main>'
```

If I install the gem, it works:

```
$ sudo gem install logger-application
Fetching: logger-application-0.0.2.gem (100%)
Successfully installed logger-application-0.0.2
Parsing documentation for logger-application-0.0.2
Installing ri documentation for logger-application-0.0.2
Done installing documentation for logger-application after 0 seconds
1 gem installed

$ ruby /usr/local/bin/xsd2ruby.rb
Usage: /usr/local/bin/xsd2ruby.rb --xsd xsd_location [options]
  xsd_location: filename or URL

Example:
  /usr/local/bin/xsd2ruby.rb --xsd myapp.xsd --classdef foo

Options:
  --xsd xsd_location
  --classdef [filenameprefix]
  --mapping_registry
  --mapper
  --module_path [Module::Path::Name]
  --force
  --quiet
```

**Comment by rubyjedi** [comment]
Fixed as of 2.1.0: `soap4r-ng.gemspec` now declares `logger-application` (and `httpclient`) as runtime dependencies via `s.add_runtime_dependency`, so `gem install soap4r-ng` pulls it in automatically -- no manual `gem install logger-application` step needed anymore. The gemspec comment explicitly cites this issue as the reason. Verified against the current bin/xsd2ruby.rb and bin/wsdl2ruby.rb, both of which require logger-application at load time.
