### ISSUE TITLE
rspec running tests uninitialized constant SOAP::SOAPString::EncodingNamespace error

### ISSUE THREAD

**Issue by MysteriousNothing** [rubyjedi/soap4r#25]
Hello, I have problem with old project when running rspec
I get

Ruby 2.3.1
Rails 4.2.6

 ```
An error occurred while loading spec_helper.
Failure/Error: require File.expand_path(File.dirname(__FILE__) + "/../config/environment")

NameError:
  uninitialized constant SOAP::SOAPString::EncodingNamespace
  Did you mean?  EncodingError
# /home/henry/.rvm/gems/ruby-2.3.1/bundler/gems/soap4r-96aa5490a74f/lib/soap/baseData.rb:259:in `<class:SOAPString>'
# /home/henry/.rvm/gems/ruby-2.3.1/bundler/gems/soap4r-96aa5490a74f/lib/soap/baseData.rb:256:in `<module:SOAP>'
# /home/henry/.rvm/gems/ruby-2.3.1/bundler/gems/soap4r-96aa5490a74f/lib/soap/baseData.rb:16:in `<top (required)>'
# /home/henry/.rvm/gems/ruby-2.3.1/bundler/gems/soap4r-96aa5490a74f/lib/soap/mapping/registry.rb:10:in `require'
# /home/henry/.rvm/gems/ruby-2.3.1/bundler/gems/soap4r-96aa5490a74f/lib/soap/mapping/registry.rb:10:in `<top (required)>'
# /home/henry/.rvm/gems/ruby-2.3.1/bundler/gems/soap4r-96aa5490a74f/lib/soap/mapping.rb:11:in `require'
# /home/henry/.rvm/gems/ruby-2.3.1/bundler/gems/soap4r-96aa5490a74f/lib/soap/mapping.rb:11:in `<top (required)>'
# /home/henry/.rvm/gems/ruby-2.3.1/bundler/gems/soap4r-96aa5490a74f/lib/soap/rpc/driver.rb:12:in `require'
# /home/henry/.rvm/gems/ruby-2.3.1/bundler/gems/soap4r-96aa5490a74f/lib/soap/rpc/driver.rb:12:in `<top (required)>'
```

I'm not sure why projects broke.

Anyone has Ideas what to do?

**Comment by MysteriousNothing** [comment]
I'm sorry, Rails lib folder had folder soap. and file soap.rb which overwrite something
